# -*- coding: utf-8 -*-
"""UpdateVotes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14MszdpTrEdiBrUDMvA0WAWS8lgXM1-G5
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
url = "https://earlyvotecounts.bexar.org/"

response = requests.get(url)
if response.status_code == 200:
  print(response)
else:
  exit()

html = BeautifulSoup(response.content, 'html.parser')
html_summary = html.find(id = "evcounts")

df = pd.read_html(str(html_summary))[0]
df

dfprime = pd.read_excel('2023-10-23.xlsx')

dfprime

dfprime['Daily  Total Votes'] = df['Daily Total Votes']
dfprime['Previous  Total Votes'] = df['Previous Total Votes']
dfprime['Total Votes  TO DATE'] = df['Total Votes TO DATE']

total_vote_sum = dfprime['Total Votes  TO DATE'].sum()
dfprime['Total Total'] = total_vote_sum
dfprime['Percentage'] = dfprime['Total Votes  TO DATE'] / dfprime['Total Total']
dfprime['Traffic Weight'] = dfprime['Percentage'] * -1
dfprime

dfprime.to_excel("2023-10-24.xlsx")

# xlsx = ExcelFile('Locations.xlsx')
# df = xlsx.parse(xlsx.sheet_names[0])
# df.to_dict()